name: Build and Test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Lint
      uses: golangci/golangci-lint-action@v6
      with:
        args: -p bugs -p unused
    - name: Set up Go 1.22
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.x'
    - name: Test
      run: |
        make test
    - uses: release-drafter/release-drafter@v6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
