name: Build and Test

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Lint
      uses: golangci/golangci-lint-action@v2
      with:
        args: -p bugs -p unused
    - name: Set up Go 1.19
      uses: actions/setup-go@v3
      with:
        go-version: '1.19.x'
    - name: Test
      run: |
        make test
